version: "3.8"

services:
  frontend:
    image: frontend
    build: ./example-frontend
    container_name: frontend
    ports:
      - 5000:5000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

  backend:
    image: backend
    build: ./example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      REQUEST_ORIGIN: http://localhost:5000
      PORT: 8080
