version: "3.8"

services:
  frontend:
    image: frontend
    build: ./example-frontend
    container_name: frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost

  backend:
    image: backend
    build: ./example-backend
    container_name: backend
    depends_on:
      - postgres
      - redis
    environment:
      REQUEST_ORIGIN: http://localhost
      PORT: 8080
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  redis:
    image: redis:7.2-rc1
    container_name: redis

  postgres:
    image: postgres:15.2
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  proxy:
    image: nginx:1.23.4
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
