name: E3-1

on:
  push:
    branches:
      - master

jobs:
  build-n-push:
    name: Publish image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./part3/e3-1/express-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-app:latest
